Sage-Bionetworks/aws-infra

cf_templates/vpc.yml
Got a better vpc template from awslabs[1]
[1] https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/VPC/VPC_With_Managed_NAT_And_Private_Subnet.yaml
=> update vpc template

cf_templates/vpc.yml
Setup subnets to larger range of IPs and put subnets in separate
availability zones.
VPC layout: https://imgur.com/a/kGr1q
=> Configure subnets

cf_templates/vpc.yml
Now you can create or update a VPC with a more meaningful
name.  Pass the param like so:
aws cloudformation update-stack \
--stack-name vpc \
--capabilities CAPABILITY_NAMED_IAM \
--template-body vpc.yml \
--parameters \
ParameterKey=VpcName,ParameterValue="Synapse-Prod"
=> parameterize the VPC name

cf_templates/vpc.yml
Add two additional public and private subnet to the vpc.
diagram: https://imgur.com/a/FH1Mm
=> Setup additional public and private subnet

README.md, cf_templates/peer-route-config.yml
Configure the peering connection on the VPC to the VPN which will
allow the VPN to direct traffic to the VPC.
=> Configure peering connection

.gitignore, README.md, cf_templates/bootstrap.yaml, cf_templates/essentials.yaml, cf_templates/peer-route-config.yaml, cf_templates/vpc.yaml
Change CF filenames to .yaml extension because sceptre requires it.
=> Change yml to yaml

templates/jumpcloud.yaml
Send an alarm when the jumpcloud clean system lambda fails.
=> jumpcloud lambda alarm

.travis.yml, lambdas/rotate-credentials/expire_access_key/app.py, lambdas/rotate-credentials/template.yaml
Refactor the RotateCredentials lambda to a SAM application.
This is the only way to make cloudformation deploy updated
lambda code.
=> [IT-295] Deploy lambda with SAM template

.travis.yml, templates/RotateCredentials.yaml
restore original templates/RotateCredentials.yaml file to keep
dependent projects happy.  Setup build of SAM template
rotate-credentials.yaml to the new version of this lambda.
=> restore RotateCredentials.yaml

.travis.yml, templates/AccountAlertTopics.yaml
Fix the following template errors:
W1001 Ref to resource "SNSAlertsError" that many not be available when
when condition "cDeployLambda" is False at
Resources/SNSAlertPolicy/Properties/Topics/1/Ref
=> Fix template errors in AccountAlertTopics.yaml

ci/s3web-bucket-input.json, ci/s3web-cloudfront-bucket-input.json, ci/taskcat.yaml, templates/managed-s3Web.yaml, templates/managed-s3WebCloudfront.yaml
Moving 2 templates to aws-infra so they can be shared.
=> Move templates to aws-infra.

templates/R53-hostedzone.yaml, templates/acm-certificate.yaml
Add templates to allow provisioning of ACM certificates and
hosted zones.
=> Templates for setting up Route53

templates/essentials.yaml
Setup a role for the Data lifecycle manager[1]
[1] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snapshot-lifecycle.html
=> [IT-520] Setup role for DLM

templates/managed-ebs.yaml
Add a template to allow adding and attaching additional ebs
volumes to EC2 instances.
=> Template to provision an EBS volume

templates/managed-ec2-win-v1.yaml
Add a template to allow users to provision a secure Windows EC2
instance.
=> [IT-512] Template to provision a Windows EC2 instance

templates/managed-ec2-v7.yaml, templates/managed-ec2-win-v2.yaml
* Validate that Department and Project parameter does not contain spaces.
* Validate the email syntax of the OwnerEmail parameter.
=> [IT-545] validate tags parameters

templates/managed-alb-https.yaml
Add a generic template to allow setting up an application load balancer
to front an EC2 instance listening on https port.
=> Template for an application load balancer

ci/taskcat.yaml
Need to comment out tests due to a bug with taskcat:
https://github.com/aws-quickstart/taskcat/issues/278
=> comment out tests

lambdas/jumpcloud/clean_systems/requirements.txt
Fix the requirements definition syntax for the jumpcloud lambda.
=> fix jumpcloud lambda

.gitignore, .travis.yml
* Lambdas using the SAM framework should be built and packaged with
the SAM CLI.
* The build command must be run if packaging 3rd party
libraries with lambdas.
=> [IT-452] build and package using SAM CLI

templates/essentials.yaml
@zaro0508 Export the role we talked about this morning for use in the list of roles that make up the toil instance profile.
=> Export TagRootVolumeRole

lambdas/rotate-credentials/template.yaml
Setup deadletter queue[1] for SAM based lambda to send notifications to
[1] https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#deadletterqueue-object
=> [IT-305] Setup dead letter queue for lambda

templates/managed-alb-https.yaml
Output load balancer name as it is needed by code deploy.
=> Output load balancer name

templates/managed-ec2-linux-v1.j2, templates/managed-ec2-ubuntu-v1.yaml, templates/managed-ec2-ubuntu-v2.j2, templates/managed-ec2-ubuntu-v3.j2, templates/managed-ec2-v10.j2, templates/managed-ec2-v7.yaml, templates/managed-ec2-v8.j2, templates/managed-ec2-v9.j2, templates/managed-ec2-win-v1.yaml, templates/managed-ec2-win-v2.yaml, templates/managed-ec2-win-v3.j2, templates/managed-ec2-win-v4.j2
Some people have requested instances with more than 1TB disk.
=> increase volume size limit

templates/managed-ec2-win-v4.j2
Use the Windows EC2 provisioner scripts with fix in
PR https://github.com/Sage-Bionetworks/infra-utils/pull/39
=> Update windows EC2 provisioner scripts

lambdas/jumpcloud/template.yaml, lambdas/rotate-credentials/template.yaml, templates/AccountAlertTopics.yaml, templates/AddSameRegionBucketDownloadRestriction.yaml, templates/acm-certificate.yaml, templates/bootstrap.yaml, templates/essentials.yaml, templates/managed-alb-https.yaml, templates/managed-batch.yaml, templates/managed-ebs.yaml, templates/managed-ec2-linux-v1.j2, templates/managed-ec2-ubuntu-v1.yaml, templates/managed-ec2-ubuntu-v2.j2, templates/managed-ec2-ubuntu-v3.j2, templates/managed-ec2-v10.j2, templates/managed-ec2-v7.yaml, templates/managed-ec2-v8.j2, templates/managed-ec2-v9.j2, templates/managed-ec2-win-v1.yaml, templates/managed-ec2-win-v2.yaml, templates/managed-ec2-win-v3.j2, templates/managed-ec2-win-v4.j2, templates/managed-s3Web.yaml, templates/managed-s3WebCloudfront.yaml, templates/periodic-batch-scheduler.yaml, templates/s3-bucket.yaml, templates/vpc.yaml
Add tags to resources that support tags.  Cloudformation does not
recreate resources when applying new tags or updating existing tags.
=> [IT-623] add missing tags to resources

lambdas/rotate-credentials/expire_access_key/app.py, lambdas/rotate-credentials/template.yaml
Add an api gateway for rotate credentials lambda so it can be triggered
from a url endpoint.
to trigger the lambda:
```
curl https://<restapiid>.execute-api.us-east-1.amazonaws.com/Prod/check/
```
=> api gateway for rotate credentials lambda

templates/AddSameRegionBucketDownloadRestriction.yaml, templates/s3-bucket.yaml
* Add SameRegionResourceAccessToBucketGrantVpcAccess to S3 bucket
template which was added by commit e90751e
* Update AddSameRegionBucketDownloadRestriction.yaml template
* Add comments to AddSameRegionBucketDownloadRestriction.yaml template
=> [IT-661] Add new parameter to s3 bucket template

.travis.yml
Use bionic build machine so we can use snap repos.
https://docs.travis-ci.com/user/installing-dependencies/#installing-snap-packages-with-the-snaps-addon
=> update travis instance

.travis.yml
This change should let travis run taskcat v0.9 without error
=> Update travis to work with taskcat v0.9

.travis.yml
Trying to migrate from taskcat v0.8 to v0.9.
=> Update taskcat cmd string

.travis.yml, ci/taskcat.yaml
Taskcat parameters have changed and I want to test if this change results in the same tags as before
=> Testing new taskcat string

.travis.yml, ci/.taskcat.yml
Taskcat tags function has changed format
=> Fix taskcat tagging fn

ci/.taskcat.yml
More changes... project seems to be the correct parameter for our case
=> taskcat global vs. project

ci/.taskcat.yml
use general keyword rather than global
=> revert taskcat global to general

ci/.taskcat.yml
=> Try taskcat project definition

ci/.taskcat.yml
Default package_lambda is true; removing from config
=> Remove package_lambda default

ci/.taskcat.yml
=> Update key/value def

ci/.taskcat.yml
=> Update tag def

ci/.taskcat.yml
external parameters requires parameter_input
=> Revert to parameters_file

.travis.yml, lambdas/cfn-explode-macro/explode/app.py, lambdas/cfn-explode-macro/template.yaml
Add and deploy the explode macro to help do post processing of
templates.  The macro is from AWS here:
https://github.com/awslabs/aws-cloudformation-templates/tree/master/aws/services/CloudFormation/MacrosExamples/Explode
=> Add cloudformation macro

.travis.yml
Forgot to add cfn-ssm-param-macro to travis
=> Add cfn-ssm-param-macro to travis

lambdas/cfn-ssm-param-macro/template.yaml
remove execution role and policy
change macro function role to one just defined in bootstrap
=> Remove inline execution role and policy from cfn-ssm-param-macro

templates/vpc.yaml
Export VPN CIDR from VPC template
=> Export VPN CIDR used when setting up VPC security group ingress

lambdas/cfn-ssm-param-macro/template.yaml
export function name and arn for SsmParam
=> Output SsmParam function name and arn

templates/s3-bucket.yaml
output the Synapse bucket ARN to more easily reference provisioned buckets
from other cloudformation stacks.
=> output bucket ARN

.travis.yml, lambdas/cfn-sc-actions-provider/README.md, lambdas/cfn-sc-actions-provider/events/actions.txt, lambdas/cfn-sc-actions-provider/events/create.json, lambdas/cfn-sc-actions-provider/events/delete.json, lambdas/cfn-sc-actions-provider/events/response-failed.json, lambdas/cfn-sc-actions-provider/events/response-success.json, lambdas/cfn-sc-actions-provider/events/update.json, lambdas/cfn-sc-actions-provider/sc-actions-provider/app.py, lambdas/cfn-sc-actions-provider/sc-actions-provider/associate.py, lambdas/cfn-sc-actions-provider/sc-actions-provider/requirements.txt, lambdas/cfn-sc-actions-provider/template.yaml
This implements a custom resource to allow us to automate
the creation/deletion/update of service catalog actions using
cloudformation. In addition it also allows us to use cloudformation
to associate SC actions to SC products.
=> [SC-26] CFN custom resource for SC actions

templates/managed-ec2-linux-v2.j2
Remove items that are added to the base-ubuntu-bionic AMI:
Remove cnf helper script install:
* https://github.com/Sage-Bionetworks-IT/packer-base-ubuntu-bionic/pull/20
Remove install jq:
* https://github.com/Sage-Bionetworks-IT/packer-base-ubuntu-bionic/pull/21
* https://github.com/Sage-Bionetworks-IT/packer-base-amazonlinux2/pull/6
=> [IT-852] refactor managed ec2 template

templates/s3-bucket.yaml
The AddSameRegionBucketDownloadRestriction lambda was updated and a new tag
was created.  Use the new version.
=> [SYNPY-1054] bump AddSameRegionBucketDownloadRestriction version for S3 bucket

templates/maintenance.yaml
This defines a single scheduled task that runs in an account every week and operates on specifically tagged resources.
=> SC-12, moved to general aws-infra

templates/sumologic-role.yaml
Sumologic requires an update to it's role
=> update sumologic role

templates/bootstrap.yaml
output of role id will allow setting access to a aws:userid
"Principal Key Value"[1]
[1] https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html
=> [IT-937] output the CF service role id

templates/ssm-parameters.j2
Jinja uses {#...#} syntax for block comments
=> Fix comments for jinja templates

templates/IAM/service-account.yaml
Add a shared template to setup service accounts
=> template for service accounts

templates/EFS/efs.yaml
Add a cloudformation template to create an elastic file system.
=> [SC-306] EFS template

templates/VPC/efs-vpc.yaml
Add a template to create a VPC to deploy an EFS file system into
depends on #282
=> [SC-306] VPC for EFS

templates/IAM/jumpcloud-idp.yaml
Switch to using the official cloudformation SAML resource provider
=> [IT-1137] Use AWS provided CFN SAML resource

templates/Cloudtrail/cloud-trail.yaml
Add a template to create a cloudtrail trail.
=> [IT-1101] Cloudtrail template

templates/SSO/aws-sso.yaml
This is to allow us to manageme AWS SSO with org-formation.
=> [IT-1178] ofn AWS SSO template

templates/Cloudwatch/cloudwatch-log.yaml
Allow users to pass in a custom log group name.
=> parameterize LogGroupName

templates/IAM/managed-policy.yaml
Add a template to allow creating a custom managed policy so it
can be used as an input to another resource, like a user or role.
=> [IT-1178] Template to create a custom managed policy

templates/Cloudtrail/cloudtrail-trail.yaml, templates/Config/config.yaml
Add cloudformation outputs for cloudtrail and config buckets so it can
be re-used elsewhere.
=> Output aws cloudtrail and config bucket info

templates/s3-bucket-v2.j2
fixed whitespace in s3-bucket-v2.j2
=> Fixed whitespace in s3-bucket-v2.j2

.travis.yml
Setup CI to run a linter[1] on jinja templates.
[1] https://github.com/drm/jinja2-lint.git
=> [IT-1332] lint jinja templates

templates/VPC/vpc-20-private.yaml
https://sagebionetworks.jira.com/browse/IT-1376
We need a second public subnet in vpc-20-private for ALB.
=> Convert the fifth private subnet to a public subnet in vpc-20-private

templates/EC2/jc-ec2-win.j2
* Add security group to allow access from VPN
* Add role and tags to allow security maintenance tasks
=> Update windows EC2 template

templates/EC2/basic-ec2.j2
Add  tags to allow security maintenance tasks
=> Update basic EC2 template

templates/ORG/password-policy.yaml
[ X ] Add all possible elements to policy statement and increase strictness
[ X ] Passes pre-commit
=> More strict IAM password policy

templates/ORG/password-policy.yaml
[ X ] Add missing passwd reuse rule
[ X ] Passes pre-commit
=> [IT-1793] Include PasswordReusePrevention

templates/essentials.yaml
Enable key rotation for KMS key
=> [IT-2318, IT-2325] Enable KMS key rotation

templates/essentials.yaml
This PR gives access to the infra key to the OIDC role.
=> IT-2308: Fix per review

templates/R53-hostedzone.yaml, templates/acm-certificate.yaml
These tags are not used, remove them before creating new resources from these templates.
=> Remove deprecated Project, Depantment, and OwnerEmail tags

.github/workflows/deploy.yaml
This PR sets the role duration to 900 (min per error msg).
=> IT-2672: Fix duration on credentials action

.github/workflows/deploy.yaml
This PR fixes the reference to branch for the push test.
=> IT-2672: Fix ref for push

templates/NextflowTower/nextflow-launch.yaml
Setup a template to to launch nextflow tower projects. This template will be used by the nextflow-infra repo[1]
[1] https://github.com/Sage-Bionetworks-Workflows/nextflow-infra
=> [IT-2361] Add template for Nextflow tower

templates/IAM/snowflake-bucket-access.yaml, templates/IAM/snowflake-synapse-access.yaml
This PR is a parameterized version of https://github.com/Sage-Bionetworks-IT/organizations-infra/blob/master/sceptre/synapseprod/templates/snowflake-access.yaml (added 'Stack' parameter).
=> PLFM-8005: Added stack parameter to original version in orginfra

templates/vpc.yaml
PR Checklist:
[ ] Describe and explain your intentions for this change
[ ] Setup pre-commit and run the validators (info in README.md)
To validate files run: `pre-commit run --all-files`
=> IT-4226: The name of the VPC endpoint needs to be lowercase

templates/ImageBuilder/cis-for-eb-image-pipeline-template.yaml
Updates requested in #425  (already mereged).
=> PLFM-8908: updates from CR on previous PR

templates/ImageBuilder/cis-for-eb-image-pipeline-template.yaml
Changes to CIS hardened server required by CIS-5.1.1.4 and CIS-5.1.1.3 compliance findings
See 
https://sagebionetworks.jira.com/browse/SAGL-65
https://sagebionetworks.jira.com/browse/SAGL-72
=> SAGL-72: Changes to CIS hardened server required by CIS-5.1.1.4 and CIS-5.1.1.3 compliance findings

templates/ImageBuilder/cis-for-eb-image-pipeline-template.yaml
CIS-4.2.6  Ensure SSH PAM is enabled
CIS-4.2.18 Ensure SSH MaxSessions is set to 10 or less
CIS-4.6.6  Ensure root password is set
CIS-4.2.20 Ensure SSH Idle Timeout Interval is configured
=> CIS Image pipeline: Adding changes for CIS compliance scan findings

templates/S3/s3-apex-redirector.yaml
Add a template to setup a redirect from one apex domain to another
For example: redirect all traffic from my-site.org to mysite.org
=> [IT-4498] Template to setup redirect
