cf_templates/vpc.yml
Sophos setup video[1] says public and private subnet must be in the
same availability zone otherwise we will not be able to connect two
subnets to the same instance (the sophos utm instance).
[1] https://www.youtube.com/watch?v=7vjgVUUJyIc @ 5:40
=> Sophos requires subnets to be in the same AZ

deploy_infra.sh
Files larger than 51K can only be validated if it's in an
S3 bucket[1] so we need to upload to S3 then validate with an
S3 url reference.
[1] https://docs.aws.amazon.com/cli/latest/reference/cloudformation/validate-template.html#options
=> Validate templates larger than 51K

cf_templates/essentials.yml
When you request a VPC peering connection from one AWS account
(requester_account) to a VPC in another AWS account (a peer_account),
the VPC peering connection request must first be approved and accepted
by the peer_account to be activated. By default, the requester_account
cannot both request and also approve VPC peering connection requests
made to a different AWS peer_account.  AWS knowledge base article[1]
explain how to automate the approval of a peering request.  This CF
template code is from the awslabs repo[2]. Make it an essential resource
to every Sage VPC.
[1] https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-peering-vpc-different-account/
[2] https://github.com/awslabs/aws-cloudformation-templates/tree/master/aws/solutions/VPCPeering
=> Automate VPC Peering request

cf_templates/vpc.yml
Add security group to allow VPN traffic from the sophos VPN. This
allows the sophos VPN to give users access to AWS resources.
To give VPN users access to an AWS resouce this security group
must be added to that resource.
=> Setup VPN security group

cf_templates/vpc.yml
Setting the outbound rule to VPC.Cidr block doesn't allow resources
in the private subnet to access the internet.  It should be set to
"0.0.0.0/0".
=> Fix VPN security group

deploy_infra.sh
CF templates were gettting promoted even on validation errors.
Separate the validation and promotion step and make script stop
on any failure so that we either promote all templates or none.
=> Fix template promotion

cf_templates/essentials.yml
The process to run lambda code (python) with dependencies is to package
the code (including it's dependencies) into a zip file.  Upload the
zip file to an S3 bucket then reference the zip file from a
cloudformation script[1].  This change just creates the bucket to store
the lambda artifacts.
[1] https://github.com/awslabs/serverless-application-model/blob/master/HOWTO.md
=> Bucket to store lambda artifacts

cf_templates/essentials.yml
Create a KMS key that will be used to encrypt/decrypt variables in AWS.
This will allow us to migrate from using git-crypt to using KMS to manage
secrets.
=> Setup a KMS key for infra parameters

README.md, templates/bootstrap.yaml
It is an AWS security best practice[1] to execute tasks requiring elevated
permissions thru roles.  Refactor the travis user to deploy CF templates
thru a role.  This is more secure because roles execute tasks using
temporary one time access keys.
TODO: Modify the CI group permission to ReadOnlyAccess to force CI
users to use the CF service role to deploy templates.
[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-servicerole.html
=> Setup a role for CF deployments

templates/bootstrap.yaml
Change CI group policy (which includes travis user) from admin to
read only.  The purpose is to make travis deploy CF templates
using the CF service role.
!Important: this will break CF deployment on *-infra repos that
have not been prepped[1] to use the CF service role.
[1] https://github.com/Sage-Bionetworks/aws-infra/pull/40
=> Make travis deploy with CF service role

templates/bootstrap.yaml
This reverts commit bdbd75dc5547ceba8306d9ace286a64f5d5908bd.
Non cloudformation projects (BridgePF, BridgeResearchUI, etc..)
use the travis s3 provider[1] to deploy artifacts. Changing
the travis user to read only breaks deployment on those projects.
[1] https://docs.travis-ci.com/user/deployment/s3/
=> Revert "Make travis deploy with CF service role"

templates/GuardDutyMember.yaml
setup guard duty in master/member configuration[1]. This
will setup the members. The template to setup the master
is in Sage-Bionetworks/logcentral-infra repo.
[1] https://aws.amazon.com/blogs/security/how-to-manage-amazon-guardduty-security-findings-across-multiple-accounts/
=> Setup guard duty members

templates/essentials.yaml
All infra projects are now using the CF service role instead of the
travis to deploy.  Now we change access to the KMS key to the CF
service role as well.
This change requires a two step deployment process:
deploy 1: keep `us-east-1-bootstrap-TravisUser`
deploy 2: remove `us-east-1-bootstrap-TravisUser`
=> update kms infra key access

templates/AccountAlertTopics.yaml
Add a template to create general notifications for each AWS account.
The notifications are published to SMS, Email, and Slack channel.
Setting up SMS and slack notifications are optional.
The idea is to setup these general SNS topis then have alarms
for various services publish to these topics.  These will serve
as generic notifications for any aws resource.
=> Add template for general notifications

.gitignore, .travis.yml, lambdas/RotateCredentials/ExpireAccessKeyLambda.py, templates/RotateCredentials.yaml
Lambda script to setup a IAM user access key rotation schedule.
This script is not designed to actually auto rotate keys. It's
designed to make the IAM user rotate their own keys because
there is no mechanism to auto rotate keys on behalf of another user
in AWS.
This scrip does two things:
1. Notify users when their key is about to expire and ask them to
rotate their key themselves.
2. Upon key expiration it will automatically deactivate keys and
notify users that they will need to rotate their expired keys.
It's designed to expire keys on the same schedule as user passwords.
For example if the AWS account is configured to expire user passwords
every 90 days then access keys will also be set to expire every 90
days.  It's designed to review only IAM users with AWS console
access (human …
=> add lambda to setup access key rotation schedule

lambdas/RotateCredentials/ExpireAccessKeyLambda.py
The expire IAM key lambda assumes that the IAM username is an email
address. Not all AWS accounts are setup with email addresses for the
username. Validate that the username for an AWS IAM account is an email
address before sending an email to the user.
=> Validate username is an email address

templates/bootstrap.yaml
An instance profile is not needed and it is not used by any dependent
resources.
=> remove CF service instance profile

templates/bootstrap.yaml
Most project don't need versioning on the cloudformation bucket so
make it optional.
=> [IT-295] optional CF bucket versioning

templates/essentials.yaml
AWS config reports non-compliance in all our aws accounts due to
a misconfigured aws config rule.
In each aws account we have setup cloudtrail to send logs to a
central S3 bucket in our aws org-sagebase-logcentral account
(essentials-awss3cloudtrailbucket-1jz6pf8dzid7r). However the
aws config rule was setup to look for the cloudtrail logs in a
local bucket.
To fix the issue we re-configure the config rule to look for
logs in the central s3 bucket.
=> [it-395] Fix aws config non-compliance

templates/sumologic-role.yaml
Sumo logic recommends setting up a role to allow access to the S3
buckets in our AWS account.  This is to allow sumo to ingest
logs from those buckets.
=> Add shared template for logging service

lambdas/RotateCredentials/ExpireAccessKeyLambda.py, templates/RotateCredentials.yaml
The lambda broke because 'enable password expiration' was disabled
in synapsedev and synapseprod accounts.  The lambda uses the
PasswordPolicy.MaxPasswordAge as the expiration age.  Since it was
disabled the API response did not contain that key.  We now de-couple
the password expiration age from the access key expiration age.
The expiration period for password and access key are now independent
and the key expiration age is passed in from the template that
deploys the rotate credentials lambda.
=> [IT-427] Fix rotate credentials lambda

.travis.yml, templates/AccountAlertTopics.yaml, templates/essentials.yaml, templates/jumpcloud.yaml, templates/vpc.yaml
Fix up the following lint errors:
E3012 Property Resources/SpendingAlarm/Properties/Period should be of type Integer
./templates/AccountAlertTopics.yaml:111:7
E3012 Property Resources/SpendingAlarm/Properties/EvaluationPeriods should be of type Integer
./templates/AccountAlertTopics.yaml:112:7
E3012 Property Resources/SlackNotificationLambda/Properties/Timeout should be of type Integer
./templates/AccountAlertTopics.yaml:152:7
W2511 IAM Policy Version should be updated to '2012-10-17'.
./templates/essentials.yaml:75:9
W3005 Obsolete DependsOn on resource (AWSLogsCloudtrailLogGroup), dependency already enforced by a "Fn:GetAtt" at Resources/AWSCloudtrailTrail/Properties/CloudWatchLogsLogGroupArn/Fn::GetAtt/['AWSLogsCloudtrailLogGroup', 'Arn']
./templates/essentials.yaml:119:5
W3005 …
=> [IT-446] validate templates on PRs

templates/ParkMyCloud.yaml
Add a template to allow AWS and ParkMyCloud (PMC) integration.
PMC is a separate portal to allow users to start and stop AWS
resources. It will be used as a library by other
Sage-Bionetworks/*-infra projects.
=> [IT-433] CF template for ParkMyCloud integration

.gitignore, .travis.yml, README.md, ci/AccountAlertTopics-input.json, ci/AddSameRegionBucketDownloadRestriction-input.json, ci/ParkMyCloud-input.json, ci/bootstrap-input.json, ci/jumpcloud-input.json, ci/sumologic-role-input.json, ci/taskcat.yaml, ci/vpc-input.json
Use taskcat[1] to test cloudformation templates.  Taskcat tests
templates by deploying resources to an AWS account then tearing
them all down afterwards.  This makes sure that templates can actually
provision resources to the AWS account in a specified AZ.  We
only test on "us-east-1" because that's the only AZ we use.
Taskcat is a bit opinionated about it's directory structure so
we could not include the rotate-credentials lambda.  We also
have a few issues with CF templates that make them difficult to test:
https://sagebionetworks.jira.com/browse/IT-475
https://sagebionetworks.jira.com/browse/IT-476
[1] https://github.com/aws-quickstart/taskcat
=> Setup cloudformation tests with taskcat

templates/s3-bucket.yaml
This is a DRY refactor.  The SynapseExternalBucket template is
duplicated in multiple repos. Move it to this repo so it can be shared
by sandox-provisioner and sciomp-provisioner repos.  We also rename
it because this script can actually provisions generic buckets as well
as synapse specific buckets.
=> [IT-488] share templates

templates/s3-bucket.yaml
Users may only want to provision a generic bucket.  The SynapseUserName
parameter is not applicable in those cases.  Do not not deploy a
owner.txt file in those cases.
This requires refactoring the sceptre "synapse_bucket_notify" hook[1] to
not create an owner.txt file when `synapse_username` is not specified.
[1] https://github.com/Sage-Bionetworks/sceptre-provisioner-hooks/pull/4
=> [IT-497] make SynapseUserName an optional parameter

templates/essentials.yaml
Setup roles and profiles to give EC2 instances permission to
tag it's own root volume.  This will allow us to tag the volume
using the instance UserData[1].  We need to apply tags to volumes
so we can use the Data Life Cycle Manager[2] to automatically create
snapshots.
[1] https://stackoverflow.com/a/24123651
[2] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snapshot-lifecycle.html
=> [IT-520] Roles and profiles for tagging volume

ci/ec2-backup-input.json, ci/taskcat.yaml, templates/ec2-backup.yaml
Add a cloudformation template to enable backing up EC2 instances
using the data lifecycle manager[1].  This is template is meant to be
used as a nested template.
[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dlm-lifecyclepolicy.html
=> [IT-520] Add CF template to backup EC2

templates/dlm-role.yaml
Create a scheduled backup using the data lifecycle manager requires
a role.  We create a generic role for the DLM so we can provision
multiple DLM instances on each account.
=> [IT-520] setup a role for DLM

templates/managed-ec2-v7.yaml
This is a DRY refactor.  Move EC2 provisioner template from
Sage-Bionetworks/sandbox-provisioner/templates/managed-ec2-v6.yaml
to this repo so it can be shared by both sandbox-provisioner
and scicomp-provisioner.
=> [IT-488] Share EC2 provisioner template

templates/s3-bucket.yaml
As explained in these updated instructions:
https://github.com/Sage-Bionetworks/synapseDocs/pull/538/files
When an S3 bucket is to be used with Synapse it needs to grant Synapse
`S3:GetBucketLocation` permission, so Synapse can determine the Region
and configure the S3 client accordingly.
=> [IT-529] Update synapse bucket permissions

ci/managed-batch-input.json, ci/taskcat.yaml, templates/managed-batch.yaml, templates/periodic-batch-scheduler.yaml
Create CF templates to provision AWS Batch jobs.  This template will
create a batch job on two queues, a high priority and low pritority
queue. The high priority queue runs on regular instances while the low
priority queue will run jobs with spot instances.  It uses a nested
stack to provision a lambda to run the batch job on a periodic
schedule.
=> [IT-480] Add templates for AWS Batch

templates/managed-batch.yaml
Allow user to setup a batch job with a custom AMI.  This is an
optional parameter.  If you does not specify an AMI then batch
will use a default AWS AMI.
=> Allow user to use specific AMI

templates/managed-ec2-win-v1.yaml
The return code does not seem to work consistently causing the
WindowsServerWaitHandle to time.  This results in a failed
provision of windows instances.  Make it always return 0 for no
error.
The drawback here is that we may not notice a failed deployment.
I'm hoping this will be rare and we will have this issue fixed
shortly.  When fixed we should put back the `ERRORLEVEL%`
=> Set return code to 0 when deploying windows instances

templates/managed-ec2-win-v2.yaml
Update windows EC2 template.  The only difference between
v1 and v2 is an InstanceType change.  The default has
been changed from t2.small to t3.medium.  The feedback from users
using t2.small was that it was `painfully slow`
=> [IT-512] update default windows instance type

templates/managed-ec2-win-v2.yaml
Internet explorer does not work with Synapse and a bunch of other sites.
We install chrome on a provisioned windows instance so users don't have
to muck with IE.
=> [IT-512] Setup Chrome on windows instances

.travis.yml, templates/managed-ec2-ubuntu-v1.yaml
Provision an EC2 instance based off of a AWS ubuntu AMI.
differences between ubuntu template and aws linux template:
* package manager is apt instead of yum
* volume name must be "/dev/sda1" instead of "/dev/xvda"
* cfn tools come preinstalled on aws linux AMI, we need to
in stall on other distros.
=> [IT-408] support ubuntu images

templates/managed-ec2-ubuntu-v1.yaml
Deploying large instances with large volumes requires more time.
=> increase ubuntu deployment timeout

templates/managed-ebs.yaml
The "/dev/xvda" attachment location is typically the root volume
valid locations are xvd[a to z].  We mount extra volume at "xvdam"
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html
=> update managed ebs mount location

templates/managed-ec2-ubuntu-v1.yaml, templates/s3-bucket.yaml
This fixes the following linter errors:
W1020 Fn::Sub isn't needed because there are no variables at Resources/Ec2Instance/Metadata/AWS::CloudFormation::Init/configure_cfn/files//lib/systemd/system/cfn-hup.service/content/Fn::Sub
templates/managed-ec2-ubuntu-v1.yaml:427:15
E8003 Fn::Equals element must be a string, Ref, or a Fn::FindInMap
templates/s3-bucket.yaml:79:3
=> fix linter errors in templates

templates/managed-ec2-ubuntu-v1.yaml, templates/s3-bucket.yaml
This reverts commit 1d1145590b215b18a283ec96bca230f25bb6b13e.
Need to revert due to taskcat issue
https://github.com/aws-quickstart/taskcat/issues/280
=> Revert "fix linter errors in templates (#125)"

templates/managed-ec2-v8.j2
Refactor to allow provisioner to open multiple incoming ports
on an EC2 instance.  Due to the limitations with CFN we need
to convert the CFN templates to jinja[1] template to provide
this funcionality.
Example usage:
provision ec2 and open port 80, 1099, and 8020 to incoming traffic.
```
template_path: remote/managed-ec2-v8.j2
stack_name: test-ec2
OpenPorts:
- "80"
- "1099"
- "8020"
```
[1] http://jinja.pocoo.org/docs/2.10/templates/
=> [IT-567] Allow opening up multiple ports on EC2

templates/managed-ec2-ubuntu-v1.yaml, templates/managed-ec2-v8.j2
Remove support for t1 instances they are deprecated.
Add support for a1 instances for aws linux and ubuntu linux.
a1 is not supported for windows.
https://aws.amazon.com/ec2/pricing/on-demand/
=> update supported ec2 instances

templates/managed-ec2-ubuntu-v2.j2, templates/managed-ec2-win-v3.j2
Refactor EC2 scripts (ubuntu & win) to allow multiple open ports.
This increments the script version and changes them jinja templates.
This is the same as PR https://github.com/Sage-Bionetworks/aws-infra/pull/124
provision ec2 and open port 80, 1099, and 8020 to incoming traffic.
```
template_path: remote/managed-ec2-win-v3.j2
stack_name: test-ec2
OpenPorts:
- "80"
- "1099"
- "8020"
```
=> provision with multiple ports opened

templates/managed-ec2-v9.j2, templates/managed-ec2-win-v3.j2
Refactor managed-ec2 (aws linux) template:
* update default instance type from t2.nan to t3.nano
* update naming convention from camel case to undercores
* add cloudformation auto reloader service
* simplify jumpcloud setup and configuration
Refactor managed-ec2 (aws windows) template:
* simplify auto reloader using aws labs example[1]
* add awscli install to instance
* split install_jc to two steps, install and config
* add step to tag the EC2 root volume
* simplify UserData section
* replace WindowsServerWaitHandle with CreationPolicy. AWS recommends using the latter
* update naming convention from camel case to undercores
[1] https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/solutions/AmazonCloudWatchAgent/inline/windows.template)
=> Refactor ec2 templates

templates/managed-ec2-ubuntu-v2.j2, templates/managed-ec2-v9.j2, templates/managed-ec2-win-v1.yaml, templates/managed-ec2-win-v2.yaml, templates/managed-ec2-win-v3.j2
Instead of giving a group access to a provisioned EC2 we change to
only give the EC2 owner access to the provisioned instance.  Jumpcloud
configurations for AWS linux and ubuntu requests are handled in the
CFN template. Jumpcloud config for windows is handled in a powershell
script updated in PR https://github.com/Sage-Bionetworks/infra-utils/pull/33
=> [IT-553] Restrictive access to EC2 instances

templates/s3-bucket.yaml
AWS recently added support for the following S3 storage classes:
* DEEP_ARCHIVE
* INTELLIGENT_TIERING
We add support for them to the sage provisioner.
=> support addition s3 storage class

templates/managed-ebs.yaml
3.22s$ cfn-lint ./templates/**/*.yaml -i W1020
W2508 Availability Zone Parameter should be of type
[AWS::SSM::Parameter::Value<AWS::EC2::AvailabilityZone::Name>,
AWS::EC2::AvailabilityZone::Name] for Parameters/AvailabilityZone/Type
./templates/managed-ebs.yaml:16:5
=> fix cfn-linter error

templates/managed-ec2-ubuntu-v2.j2, templates/managed-ec2-v9.j2, templates/managed-ec2-win-v3.j2
Before the provisioner allowed opening multiple ports to an EC2 we
had to enable the ssh port for public instances by default.  Now
that users can specify the exact ports to open we do not need
to open ports for public instances by default.
=> [IT-567] Do not open port automatically

lambdas/rotate-credentials/template.yaml
Using python 3.6 to run the lambda results in error..
iterator should return strings, not bytes (did you open the file in text mode?): Error
Traceback (most recent call last):
File "/var/task/app.py", line 66, in lambda_handler
credential_report = get_credential_report()
File "/var/task/app.py", line 259, in get_credential_report
return get_credential_report()
File "/var/task/app.py", line 251, in get_credential_report
for row in reader:
File "/var/lang/lib/python3.6/csv.py", line 111, in __next__
self.fieldnames
File "/var/lang/lib/python3.6/csv.py", line 98, in fieldnames
self._fieldnames = next(self.reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
This stackoverflow post indicates that it's due to python 3.x: …
=> [IT-569] Fix rotate credentials lambda

lambdas/rotate-credentials/template.yaml
Nag email will be sent daily if users do not rotate their AWS key within the
grace period. Change it to default to a 7 day grace period because
14 days of nag emails is too annoying.
=> Change the default grace period to rotate aws key

templates/managed-ec2-ubuntu-v3.j2, templates/managed-ec2-v10.j2, templates/managed-ec2-win-v4.j2
* AWS now supports deploying encrypted AMI from non-encrypted AMI[1].
Add a parameter to allow users to provision an instance with an
encrypted root volume
* Occasionally googlechrome will fail to instance from chocolately repo
due to not having an updated checksum.  Use '--ignore-checksums' flag
so make it less error prone[2].  Not this is not as secure but trade
of is to make it less error prone.
* New set of version files because this change may cause AWS to replace
instances if updating existing stacks.
[1] https://aws.amazon.com/blogs/security/how-to-quickly-launch-encrypted-ebs-backed-ec2-instances-from-unencrypted-amis/
[2] https://www.gep13.co.uk/blog/chocolatey-error-hashes-do-not-match
=> [IT-583] Encrypt volume launch

templates/managed-ec2-ubuntu-v3.j2
When trying to install libssl1.1:amd64. Even if you pass apt `-y`, it
stops and prompts the user. One workaround is to
export `DEBIAN_FRONTEND=noninteractive`. Here is the confirmed
bug report: https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1832919
=> Fix issue with updating libssl

lambdas/rotate-credentials/template.yaml
Fix error:
[2019-07-03 05:03:07] - prod/rotate-credentials ExpireAccessKeyFunction
AWS::Lambda::Function UPDATE_FAILED The provided execution role does not
have permissions to call Publish on SNS (Service: AWSLambdaInternal;
Status Code: 400; Error Code: InvalidParameterValueException;
Request ID: 54b11748-a347-4817-bc9f-73cde84c6792)
Fix by allowing sns:Publish to all topics.
=> Fix lambda template

templates/managed-ec2-linux-v1.j2
The automated provisioner currently supports two linux distributions
(aws linux and ubuntu).  We manage them with 2 separate cloudformation
templates (managed-ec2-*.yaml and managed-ec2-ubuntu-*.yaml).  This
change creates one template that supports provisioning both distros.
This will make the sage provisioner easier to maintain.
To set the distro add the following to the sceptre template:
```
Distro: "ubuntu"     # AMIId must match distro
parameters:
AMIId: "ami-0a313d6098716f372"    # Ubuntu, 18.04 LTS, amd64 bionic image build on 2019-02-12
```
=> [IT-557] one template for aws and ubuntu linux

.travis.yml
Travis wasn't building tags due to the master branch restriction.
We don't need that restriction because it's already restricted
in stages section.
=> Fix tagged builds

templates/service-linked-roles.yaml
Some AWS services requires accounts to have service linked roles.
Create the roles in this template for downstream to deploy into
AWS accounts.
=> template for service linked roles

templates/service-linked-roles.yaml
Creating service linked role with 'AWS::IAM::Role' does not work.  It
will result in the following error:
```
AWSServiceRoleForEC2Spot AWS::IAM::Role CREATE_FAILED Role name prefix AWSServiceRoleFor
can only be used for AWS Service Linked Roles (Service: AmazonIdentityManagement;
Status Code: 400; Error Code: InvalidInput; Request ID: f3d2bd8e-a71f-11e9-be23-5f82a06b6aba)
```
Cloudformation has a specific resource property for service linked roles
'AWS::IAM::ServiceLinkedRole'[1] which does work.
[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-servicelinkedrole.html#cfn-iam-servicelinkedrole-customsuffix
=> Fix service linked role definition

templates/s3-bucket.yaml
This will fall back to CloudFormation's standard bucket naming strategy if a BucketName parameter is not specified.
=> Add optional bucket name to s3-bucket template

templates/service-linked-roles.yaml
Add the special role to grant the Spot Fleet permission to request, launch,
terminate, and tag instances on your behalf.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-requests.html
=> Setup special spot fleet service role

templates/essentials.yaml
Adding tags for cloudtrail resource causes failure when updating
essentials.yaml against AWS logcentral account. Error is..
prod/essentials AWSCloudtrailTrail AWS::CloudTrail::Trail UPDATE_FAILED
Incorrect S3 bucket policy is detected for bucket: essentials-awss3cloudtrailbucket-1jz6pf8dzid7r
(Service: AWSCloudTrail; Status Code: 400; Error Code: InsufficientS3BucketPolicyException;
Request ID: aaa30197-f5c6-4a33-8982-017fcef6780f)
Removing tags allows updating the template without error.
=> Remove tags for cloudtrail resource

templates/peer-route-config.yaml, templates/peer-single-route.yaml
Add AllowPattern to CIDR parameters as suggested by cfn-lint
W2509 AllowedPattern and/or AllowedValues for Parameter should be specified at Parameters/VpnCidr.
Example for AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
=> fix cfn-lint error

templates/gateway-vpc-endpoint.yaml
Add a template to provision a Gateway VPC endpoint[1]. What an endpoint
effectively does is enable instances in your VPC to use their private
IP addresses to communicate with resources in other services.
Consequently, your instances do not require public IP addresses, and
you do not need an Internet Gateway, a NAT instance, or a virtual
private gateway in your VPC. This is because you use endpoint policies
to control access to resources in other services. Traffic between your
VPC and the AWS service does not leave the Amazon network which will
reduce latency and cost.
[1] https://docs.aws.amazon.com/vpc/latest/userguide/vpce-gateway.html
=> Template for Gateway VPC endpoints

templates/bootstrap.yaml
Our CI user, travis, does not need admin permissions.  Our CI system
is already setup to have travis assume the CfService role to deploy
templates.  For better security we revoke permissions from travis.
=> [IT-666] remove CI group

templates/transit-gateway-attachment.yaml
The workflow for setting up the transit gateway it to provision the
attachments on the spoke accounts of the "hub and spoke" model
therefore this template will be used to setup every hub to
spoke attachement (aka connections).
This depends on PR https://github.com/Sage-Bionetworks/transit-infra/pull/2
=> template to setup transit gateway attachments

templates/transit-gateway-attachment.yaml
CFN updates for TGW will create a new TGW therefore it may change often.
Setting a default value makes less sense so we may users specify the
specific TGW.
=> make TransitGatewayId a required parameter

.travis.yml, ci/.taskcat.yml, ci/taskcat.yml
Pin python package to v0.8 in order to allow parameter input to remain in separate json files
=> Revert changes incompatible between taskcat v0.8 and v0.9

templates/service-linked-roles.yaml
The license manager is required for the EC2 Image Builder.
=> add service linked role for the AWS license manager

lambdas/cfn-s3objects-macro/README.md, lambdas/cfn-s3objects-macro/examples/s3bjects-example.yaml, lambdas/cfn-s3objects-macro/s3objects/macro.py, lambdas/cfn-s3objects-macro/s3objects/resource.py, lambdas/cfn-s3objects-macro/template.yaml
Add a cloudformation macro to help automate provisioning of a Synapse
storage location[1] using the service catalog.  This attempts to resolve
issue https://github.com/Sage-Bionetworks/scipoolprod-sc-lib-infra/issues/19
We got this macro from awslabs[2]
[1] https://docs.synapse.org/articles/custom_storage_location.html
[2] https://github.com/awslabs/aws-cloudformation-templates/tree/master/aws/services/CloudFormation/MacrosExamples/S3Objects
=> cloudformation macro for S3

templates/bootstrap.yaml, templates/essentials.yaml
This is a proposal to move the role used for executing the SsmParam lambda to bootstrap.yaml and export it, then make it one of the principals that can use the AWSKmsInfraKey. Setting the principal on the KeyPolicy should not require an update of the Key itself. That's the first step. 
Step 2 is to set the SsmParam lambda to use this new role.
@zaro0508 what do you think?
=> Add ssm role for lambda to bootstrap

templates/cloudwatch-cross-account-sharing.yaml
Add a template to enable one AWS account to view another account's
cloudwatch dashboard and logs.  This setup is documentented here:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Cross-Account-Cross-Region.html
=> template for sharing cloudwatch

templates/essentials.yaml
The reason for this PR is that I just discovered one cannot use more than one role in an InstanceProfile, even though its Roles field is an Array. Produces this sort of error if you do: `[2020-01-24 10:38:37] - prod/sc-ec2-linux-jumpcloud InstanceProfile AWS::IAM::InstanceProfile CREATE_FAILED Roles has too many elements. The limit is 1.`. Therefore, I need to export the tagging policy so that I can use it to create my own Role and InstanceProfile in SC.
=> Extract tagging policy into a managed policy and export

templates/ParkMyCloud.yaml
PMC added new rightsizing features for EC2, RDS and Aurora.  For
these features to work the policies need to be updated to allow
PMC to do it's tasks.
The template is referenced from:
https://parkmycloud.atlassian.net/wiki/spaces/PMCUG/pages/531202075/Create+IAM+Role+with+CloudFormation+Template
=> Update ParkMyCloud policy

templates/vpc.yaml
The prior PR didn't export the correct resource name
=> Fix typo in export name

.travis.yml, lambdas/cfn-oidc-identity-provider/README.md, lambdas/cfn-oidc-identity-provider/oidc_identity_provider/app.py, lambdas/cfn-oidc-identity-provider/oidc_identity_provider/requirements.txt, lambdas/cfn-oidc-identity-provider/template.yaml
Package and deploy a cloudformation oidc identity provier custom
resource to our shared S3 lambda bucket.  It will be used to automate
deployments of oidc identity provider resources on our AWS
accounts.
This custom resource was copied from the Mozilla security team's repo[1]
[1] https://github.com/mozilla/security/tree/master/operations/cloudformation-templates/oidc_identity_provider
=> [SC-64] oidc identity provider custom resource

templates/vpc.yaml
We don't really need these rules when we have SSM agents, but it's worth having options.
=> Add RDP ingress to quarantine SG

templates/cfn-tag-instance-policy.yaml
Move template from scipoolprod-infra to here so it can be shared and
deployed to multiple AWS accounts.  This will allow us to deploy
to an SC development account.
=> [SC-26] share templates to create sc policy

README.md, ci/AddSameRegionBucketDownloadRestriction-input.json, templates/AddSameRegionBucketDownloadRestriction.yaml, templates/s3-bucket.yaml
https://sagebionetworks.jira.com/browse/SYNPY-1054
A user in a different VPC in us-east-1 with a configured S3 VPC Endpoint Gateway is being denied access to the amp-mayo-sinai-synapseencryptedexternalbucket-1bmvn8rlwixv2 S3 bucket.
This is a modification of the behavior for [IT-661](https://github.com/Sage-Bionetworks/aws-infra/pull/173) which allowed access specifically via the S3 VPC Endpoint for the Sage computevpc.
S3 VPC Endpoints only support intra-region traffic and any S3 traffic with an aws:sourceVpc is implicitly from the same region. This changes the behavior of the region block to allow any VPC endpoint sourced request, not just a list of explicitly defined VPCs. Originally I had thought to further parameterize SameRegionResourceAccessToBucket, but I can't think of a case …
=> [SYNPY-1054] Allow all S3 VPC Endpoints to access same region restricted S3 Buckets

templates/essentials.yaml, templates/maintenance.yaml
The objective is to create a maintenance routine that operates on a cron schedule to run two tasks against EC2s with specific tags on them. The first task is to update the SSM agent on the instance;
the second is to run the AWS default patch baseline task.
This would schedule only one maintenance window: 10 am UTC every other Sunday, to run for 3 hours and reboot if needed
Depends:
Adding SSM policy to instance profiles of instances generated through SC: Sage-Bionetworks/scipoolprod-sc-lib-infra#106
Add instance profile option for instances not created in SC (not related to SC-12):
Sage-Bionetworks/aws-infra#233
=> Add scheduled maintenance tasks and add managed policy to instance profile

templates/managed-alb-https-v2.yaml
I've copied the managed-alb-https.yaml template and created a v2 version that does not listen on the AppPort. This template will only listen on 443 and forward HTTPS traffic to the target instance.
=> Remove HTTP listener

templates/managed-alb-https-v2.yaml
This is a minor change the new ALB... We have a rewrite rule for HTTP->HTTPS, but the security group on the ALB doesn't currently allow 80 inbound
=> Add port 80 ingress to allow rewrite rule to work

templates/vpc-mini.yaml
Here's one option for creating VPC peers for projects that don't use up or overlap address space among peer VPCs. This just takes our regular VPC template and reduces its subnets by one order of CIDR input. I'm suggesting that we reserve the high ranges of our address space for small subnets like this, e.g. 10.255.1..255.0/24 can fit a lot of discrete subnets. Private ranges are /26 and public ranges are /28 based on the assumption that resources are more frequently private.
We would use it like this:
````
template_path: remote/vpc-mini.yaml
stack_name: newvpcnameforproject
dependencies:
- prod/bootstrap.yaml
parameters:
VpcSubnetPrefix: "10.255.20"
VpcName: newvpcnameforproject
hooks:
before_launch:
- !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-in …
```
=> Define mini VPC template with small subnets

templates/s3-bucket-v2.j2, templates/s3-bucket-v2.yaml
Update template to support multiple user and teams.  Username in Synapse
owner file is deprecated so we change to using synapse user and team IDs.
We need to convert the v1 template to a jinja template because the synapse
owner file only supports synapse IDs on separate lines (does not support comma
separated list).  The easiest way to get the IDs on multiple lines was to use a
jinja transform.
The synapse IDs will now be passed in as a sceptre variable and it should be
passed in like so..
```
SynapseIDs: ["1300139", "3390915"]
```
=> [IT-831] Multiple synapse user and teams

.pre-commit-config.yaml, .travis.yml
cfn-lint v0.34.0 is breaking build with the following warnings:
"W4002 As the resource "metadata" section contains reference to a "NoEcho"
parameter JcSystemsGroupId, CloudFormation will display the parameter
value in plaintext.."
This will  pin cfn-lint hook to v0.33.2 so we don't get those silly warnings.
We also pin the other pre-commit hooks to the curret latest version.
=> Pin pre-commit hooks

templates/essentials.yaml
Email from AWS telling us that AWSConfigRole is being replaced by
AWS_ConfigRole.  This updates to the new role name.
As part of our continued effort to provide AWS customers with fine grained and secure
permissions management solutions, AWS Config has published a new managed policy called
AWS_ConfigRole that is scheduled to replace and subsequently deprecate AWSConfigRole
on December 1, 2020. This new policy removes the "S3:GetObject" permission as AWS
Config does not need permissions to read S3 objects.
The AWSConfigRole  managed policy will continue working for all currently attached
users, groups, and roles. However, effective December 1, 2020, AWSConfigRole managed
policy cannot be attached to any new users, groups, or roles. No action is needed if
your account does not utilize the …
=> AWSConfigRole is deprecated, replaced by AWS_ConfigRole

templates/ssm-parameters.j2
Add a cloudformation template to install parameters to the
SSM parameter store.  This is a generic jinja template that can
be used to install multiple SSM parameters into any AWS account.
This is only for non-securestring parameters.  Cloudformation
does not support adding securestring parameters into the SSM.
=> SSM parameters template

templates/transit-gateway-spoke.yaml
Add a template to setup transit gateway on the spoke end.
This template depends on a shared with ID `TransitGatewayId`.
Will require the following workflow:
1. share transit VPC (in transit account) to spoke accounts
2. accept sharing invitation in spoke account
3. run transit-gateway-spoke.yaml template to setup the spoke
account.
=> [IT-1004] Setup transit gateway spokes

templates/transit-gateway-spoke.yaml
Add a transit gateway security group to allow access to spoke VPCs from
the the HUB VPC.  The idea is to apply this SG to resources in spoke
accounts so that users can access the resource when connected to the AWS
client VPN.
=> [IT-1006] add TGW security group

templates/s3-redirector.yaml
[IT-1005] This template creates an S3 website configured with a routing rule to redirect to another website, Cloudfront is setup to handle https. Also supports an optional key to replace the incoming one. First intended use is a friendly url to the self-service portal for VPN client.
[IT-1005]: https://sagebionetworks.jira.com/browse/IT-1005
=> [IT-1005] template to create friendly redirect URL

templates/ORG/password-policy.yaml
This increases the requirements of IAM user passwords, which should be fine as they are becoming less and less commonly used.
=> Increase complexity of inputs

templates/Billing/budgets.yaml
This cfng template will allow us to use org-formation to configure
a budget for each AWS account and get notifications when budgets
are exceeding expectations.
=> [IT-1101] add template to setup aws budgets

templates/Config/config.yaml
Add templates to allow org-formation to deploy aws config in a
master member configuration[1].  This emplate is just copied
from the ofn reference project[2]
[1] https://docs.aws.amazon.com/organizations/latest/userguide/services-that-can-integrate-config.html
[2] https://github.com/org-formation/org-formation-reference/blob/master/src/templates/080-aws-config-inventory
=> [T-1101] Add templates to setup AWS master member config

templates/GuardDuty/guard-duty-extension.yaml, templates/GuardDuty/guard-duty.yaml, templates/GuardDuty/trusted-ips-bucket.yaml
These templates will allow org-formation to deploy guardduty in a
master member configuration[1].  All templates are just copied
from the ofn reference project[2]
[1] https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_accounts.html
[2] https://github.com/org-formation/org-formation-reference/tree/master/src/templates/070-guard-duty
=> [IT-1101] Add templates to setup AWS master member guardduty

templates/SCP/prevent-disable-guardduty.yaml
=> Remove restrictions on IAM users in member accounts

templates/Cloudtrail/cloudtrail-trail.yaml, templates/Cloudwatch/cloudwatch-log.yaml
Create a template to deploy a cloudwatch log group.  The output of the
log group will be passed into the cloudtrail template.  This is to
allow us to send cloudtrail logs to cloudwatch for easier viewing
and querying.
=> cloudwatch log group template

templates/essentials.yaml
We are replacing the sceptre deployment of cloudtrail with org-formation
deployment.  The essentials.yaml template is deployed with sceptre so
removing cloudtrail resources from the template.  Keep the bucket so
we can retail the old trail data.
=> [IT-1101] remove cloudtrail resources

templates/essentials.yaml
We are replacing the sceptre deployment of aws config[1] with org-formation
deployment. The essentials.yaml template is deployed with sceptre so
removing aws config resources from the template. Keep the bucket so
we can retain the old config data.
[1] https://github.com/Sage-Bionetworks-IT/organizations-infra/tree/master/org-formation/080-aws-config-inventory
=> [IT-1101] remove aws config resources

templates/IAM/service-user.yaml
In this PR, I'm adding a template for "service users", which was derived from the `IAM/service-account.yaml` template. The only difference is that I removed the IAM role resource. The use case for this template is for tools that don't support IAM roles (_e.g._ Nextflow). 
Once this PR is merged, I'll need a new tag to be minted because I plan on using this right away in [aws-workflows-nextflow-infra](https://github.com/Sage-Bionetworks-Workflows/aws-workflows-nextflow-infra). 
----
To validate files run: `pre-commit run --all-files`
=> Add service user template

templates/IAM/cross-account-access.yaml
Add a template to allow a user in another AWS account IAM access to
resources in the current account that this template is deployed to.
=> Cross account access

templates/SSO/aws-sso.yaml
AWS SSO parmeter sets does not support customer managed policies[1]
therefore we need to update the template to allow us to pass in
a inline policy.  This will allow us to define roles with custom
policies.
[1] https://forums.aws.amazon.com/thread.jspa?threadID=282793
=> update SSO template to allow setting inline policy

templates/VPC/vpc-peering-request.yaml
Add a template to create a VPC peering request role. We did this
same thing in sceptre with essentials.yaml[1], this is to decouple
the role from essentials and allows org-formation to deploy it
without all the stuff in essentials.
[1] https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/essentials.yaml#L92
=> [IT-1205] template for VPC peering request

templates/s3-bucket-v2.j2
The AWS cononical user id is the same as the AWS account id[1]
It be easier for users if we don't need them to get the cononical user
id to create buckets.
[1] https://docs.aws.amazon.com/AmazonS3/latest/userguide/finding-canonical-user-id.html
=> [IT-1295] Fix S3 bucket policy

templates/EC2/basic-ec2.j2
Add a EC2 template that will create a basic EC2 setup to allow access
using the SSM session manager.
usage from sceptre file:
```
template_path: basic-ec2.j2
stack_name: test-ec2
stack_tags:
Department: "Platform"
Project: "Infrastructure"
OwnerEmail: "it@sagebase.org"
parameters:
VpcId: !stack_output_external computevpc::VPCId
SubnetId: !stack_output_external computevpc::PrivateSubnet
OpenPorts:
- 9090
- 8090
```
=> A basic EC2 template

templates/s3-bucket-v2.j2
We had forgotten to add `OwnershipControls` setting to
SynapseEncryptedExternalBucket resource when adding that
parameter in PR #284
=> [IT-1295] Fix S3 OwnershipControls policy

templates/s3-bucket-v2.j2
This PR changes the policy statement in s3-bucket-v2.j2.  Previously the policy *always* gave Synapse access, but this change allows the stack to decide whether to give Synapse access, by including or omitting the principal in the list of grantees.  (This is how the policy originally worked.) The changes are:
- remove the SynapseBucketAccess statement. (Synapse can get access through the BucketAccess statement, along with other grantees.
- modify the SynapseObjectAccess statement so that it only applies if Synapse is in the list of grantees. (An added `Condition` ensures the statement only applies to the Synapse principal and not to other grantees.)
=> IT-1208:  Allowing omission of Synapse as a grantee

templates/VPC/vpc-20-private.yaml
Several subnets were left off the exports from the templates/VPC/vpc-20-private.yaml template. Add these.
=> Add missing subnet exports to vpc-20-private.yaml template

templates/AccountAlertTopics.yaml
Linter was complaining with the following message..
W2531 EOL runtime (python2.7) specified. Runtime is EOL since
2021-07-15 and updating will be disabled at 2021-09-30.
Please consider updating to python3.8
templates/AccountAlertTopics.yaml:173:7
=> update to python 3.8 in AccountAlertTopics.yaml lambda

templates/SSO/aws-sso.yaml
AWS has a 32 character limit on the permissionSetName.  This error
was returned when attempting to set a name that's longer that
it allowed..
ERROR: Resource PermissionSet failed because Resource handler returned message:
"Model validation failed (#/Name: expected maxLength: 32, actual: 33)"
=> Validate SSO permissionSet string length

templates/SCP/deny-all-regions-outside-us-east-1.yaml, templates/SCP/deny-all-regions-outside-us.yaml
This is the simpler of two proposed solutions to not being able to pull from eu-west-1: just allow `ecr:*` i.e. don't include it in the deny for regions outside us-east-1 and regions outside the U.S.
https://sagebionetworks.jira.com/browse/IT-1369
=> Add all ECR actions to the ones excluded from the deny policies

templates/VPC/vpc-20-private.yaml, templates/VPC/vpc-mini.yaml, templates/vpc.yaml
I'm propagating the change I made in Sage-Bionetworks-Workflows/nextflow-infra#67 to all VPC templates in this repository. The rationale is that it's free to run a VPC gateway endpoint, and we use S3 a lot at Sage. Hence, this can act as a preventative measure to avoid needless NAT gateway and inter-AZ traffic, which is costly. 
The resource and output added to each VPC template was taken from [`templates/gateway-vpc-endpoint.yaml`](https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/gateway-vpc-endpoint.yaml). The only change that I made was adding the VPC endpoint to the public route table in addition to the private route table. This will likely have no practical change since most S3 traffic is expected to originate from private subnets, but it also can't hurt to make …
=> Add S3 VPC gateway endpoints to all VPC templates

templates/EC2/jc-ec2-linux.j2
It is too unstable to allow provisioning with the latest AMIs.
Also setting to use latest AMI by default breaks the ability
to pass in an arbitrary AMI.
We should always provision instances using the AMIs built from
our packer repos: https://ami.sageit.org
=> Fix EC2 linux template

templates/EC2/jc-ec2-win.j2
This is to replace the template to provision windows instances.
* Use PropagateTagsToVolumeOnCreation[1] property to progpogate
tags applied to the EC2 onto the attached stroage volume. We
no longer need custom code to propogate tags.
* Remove tags as parameter to allow passing in tags from
cloudformation
* Move template to EC2 folder
* Add JcUserId parameter to give Jumpcloud user access to instance
[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-propagatetagstovolumeoncreation
=> Replace and update template to deploy windows EC2

templates/VPC/vpc-20-private.yaml, templates/VPC/vpc-mini.yaml, templates/vpc.yaml
We use the transit gateway to route traffic between the hub
and spoke VPCs.  To allow access to resources in a spoke VPC we need
to give the hub VPC access to the resources.  This adds an SG ingress
to resources provisioned in our spoke VPCs which will allow VPN users
access to the resources in the spoke VPCs.
=> [IT-1234] AWS Security group for TGW

templates/Cloudtrail/cloudtrail-trail.yaml
Add a parameter to the cloudtrail template to encrypt cloudtrail logs[1]
with a provided KMS key.
[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html#cfn-cloudtrail-trail-kmskeyid
=> [IT-1904] Enable cloudtrail encryption

templates/EC2/jc-ec2-linux.j2
There was a recent failure while deploying the 'jharker-test' stack in
the 'sandbox-provisioner' project during the '02_associate_jc_systems'
command. The resulting virtual machine did not have the required
association and was not accessible using ssh keys from jumpcloud.
The underlying user ID could not be found because it does not appear in the
default list of system users, but can be found when searching based on
email address.
Replace the client-side `jq` filter with a server-side api filter.
=> [IT-2052] Replace `jq` filter with api filter

templates/S3/synapse-external-bucket.j2
According to the synapse custom storage location docs[1] the
read-write permissions should contain "s3:DeleteObject" permission.
Update the policy in our templates to add that missing permission.
[1] https://help.synapse.org/docs/Custom-Storage-Locations.2048327803.html#CustomStorageLocations-Read-WritePermissions
=> Update synapse S3 bucket policy

templates/KMS/kms-key.yaml
I'm running into an [issue](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/runs/7645108962?check_suite_focus=true#step:11:145) when updating a stack that includes this KMS template as a nested stack. In CloudFormation, I found the following error. It seems like the `kms:UntagResource` is missing from [this list](https://github.com/Sage-Bionetworks/aws-infra/blob/9db3b9eb1757d9f834f841bb5b79c79a5de9ac18/templates/KMS/kms-key.yaml#L42-L53). Based on these [AWS docs](https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html#key-policy-default-allow-root-enable-iam), I wonder if we can just grant `kms:*` to the key admins. 
```
Resource handler returned message: "Access denied for operation 'UntagResource'." 
```
=> Broaden KMS admin permissions

templates/S3/synapse-external-bucket.j2
Occasionally we want to allow our external collaborators
to use the AWS CLI to upload files to buckets that we provision.
The bucket template to create an external synapse bucket does
not support that use case currently.  We need to update the
permissions to allow for that use case.
The fix is to change from BucketOwnerPreferred to BucketOwnerEnfored[1]
to disable ACLs and set the bucket owner to autmatically have full control over
every object in the bucket.
[1] https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html
=> [IT-2075] Allow bucket collaboration

templates/S3/synapse-external-bucket.j2
This is a fix to PR #351 (setting `ObjectOwnership: BucketOwnerEnforced`)
When we do that we also need to remove the ACL setting from the S3Object
macro otherwise we'll get the following error..
```
[ERROR] ClientError: An error occurred (AccessControlListNotSupported) when calling
the PutObject operation: The bucket does not allow ACLs
Traceback (most recent call last):
File "/var/task/resource.py", line 72, in handler
s3_client.put_object(**target)
File "/var/runtime/botocore/client.py", line 391, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 719, in _make_api_call
raise error_class(parsed_response, operation_name)
[ERROR] ClientError: An error occurred (AccessControlListNotSupported) when calling the
PutObject operation: …
```
=> [IT-2075] remove bucket ACL setting

templates/tags/SageFinancialProgramCodesOther.json
Restoring inactive code since it's used in some SciComp stack:
We got this error:
https://app.travis-ci.com/github/Sage-Bionetworks/scicomp-provisioner/jobs/580126789#L7435
> - config/prod/gates-ki-001.yaml: "BMGF-Ki / 30144" is not a valid CostCenter
The fix then is to restore the program code.  Can't remove it until all stacks that reference it have been updated.
=> restoring inactive code since it's used in some SciComp stack

templates/vpc.yaml
The security group is getting flagged by SecurityHub EC2.19. The proposal is to make it optional for VPCs where it's not needed (default is to have it for backward compatibility).
=> IT-2000: Make bastian sg option with default on

templates/vpc.yaml
This PR changes the default VPN CIDR from 10.1.0.0/16 to 10.50.0.0/16.
Passed pre-commit.
=> IT-2097: Change default CIDR for VPN

templates/S3/synapse-external-bucket.j2
Delete markers can get created on failed file uploads which can block users from re-uploading the same file. The user must be able to remove the delete marker before re-uploading the file. This will allow s3:DeleteObjectVersion[1] permission which will  users to remove delete markers.
[1] https://aws.amazon.com/premiumsupport/knowledge-center/s3-undelete-configuration
=> Update s3 policy to allow removing delete markers

.cfnlintrc.yaml, .pre-commit-config.yaml, .travis.yml, templates/IAM/managed-policy.yaml, templates/SSO/aws-sso.njk, templates/SSO/aws-sso.yaml
In order to use a custom managed policy for granting access to the cost explorer, we need to add support for at least one customer-managed policy to the managed-policy template. Adding support for multiple customer-managed policies in a single permission set will be more difficult due to the data structure of the parameter.
Updates to cfn-lint are required to avoid an E3002, and the updates also introduced new E2531 and E1001 occurrences - the former is a deprecation error for python 3.6, and the latter is related to org-formation syntax.
=> [IT-2268] Add support for CustomerManagedPolicyReference

templates/VPC/vpc-mini.yaml
Copy the IncludeBastianSecurityGroup parameter from the vpc template to the vpc-mini template so that we can disable access to `scheduledjobsvpc` in scipool prod.
=> [IT-2221] Add flag for bastian access to vpc-mini

templates/essentials.yaml
We initially setup cloudtrail and config buckets in individual accounts. Since then we have moved to a consolidated logging account where we aggregate all cloudtrail and config logs into buckets in the logcentral account.  We no longer need cloudtrail and config buckets created by the essentials template.
=> [IT-2272] Remove old cloudtrail and config buckets

templates/bootstrap.yaml, templates/essentials.yaml
This template is old and we shouold not be using the travis user that's created from it anymore.  We should not be using CI users that are created from org formation access deployments[1]
NOTE: This may cause build failures in travis-ci because really old CI configs might still be using these service users.  The strategy is to fix up as needed.
[1] https://github.com/Sage-Bionetworks-IT/organizations-infra/tree/master/org-formation/600-access
=> [IT-1665] Remove travis service user

templates/tags/SageFinancialProgramCodesOther.json
The BMGFKi cost center code has been removed and is no longer a valid cost center code.
=> Remove BMGFKi cost center

templates/EC2/jc-ec2-linux.j2
Use pip and venv instead of easy_install when installing aws-cfn-bootstrap to support more recent versions of Ubuntu.
=> [IT-2043] Use pip to install aws-cfn-bootstrap

templates/Config/config.yaml
The AWS built in `AWSConfigRole` has been deprecated[1] and replaced by `AWS_ConfigRole`.  
[1] https://aws.amazon.com/blogs/mt/service-notice-upcoming-changes-required-for-aws-config/
=> Update deprecated AWS config role

templates/GuardDuty/trusted-ips-bucket.yaml
Add bucket policy denying any traffic not over https to address CIS 2.1.2.
[1] https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-policy-for-config-rule/
=> [IT-2431] Require HTTPS for guard duty trusted IPs

templates/essentials.yaml
This PR removes the VPCPeeringAuthorizerRole. This role is (should not) not used anymore (grep'ed org-infra tree).
=> IT-2636: Remove VPCPeeringAuthorizerRole

templates/R53/cname.yaml
Create a template inspired by the s3-redirector template, but intended to redirect to a Cloudfront distribution created in another stack.
This is needed to create a friendly DNS name for the lambda-mips-api Cloudfront distribution.
=> [IT-2594] Create template for setting a DNS CNAME

templates/essentials.yaml
This PR removes the import for an output deleted in bootstrap in #363.
=> Remove obsolete import from bootstrap

templates/R53-hostedzone.yaml
Export the name server records for the newly created hosted zone
to support automating delegation of subdomains.
=> [DCA-37] Export HostedZone NS records

templates/R53/cname.yaml
Resolve error trying to create a CNAME record longer than 63 characters. DNS records can be 255 characters long.
=> DNS records can be 255 characters long

templates/AddSameRegionBucketDownloadRestriction.yaml, templates/bootstrap.yaml, templates/essentials.yaml, templates/managed-alb-https-v2.yaml, templates/managed-alb-https.yaml, templates/managed-batch.yaml, templates/managed-ebs.yaml, templates/managed-s3Web.yaml, templates/managed-s3WebCloudfront.yaml, templates/periodic-batch-scheduler.yaml, templates/transit-gateway-attachment.yaml, templates/vpc.yaml
Remove the Department and Project tags because we don't use them, and remove OwnerEmail because it should be applied to the entire stack and propagated to all resources within it.
We should increase the minor version to 0.7.x with this change.
=> [IT-2703] Remove old tags from template parameters

.github/workflows/deploy.yaml
The CI role names to assume will change due to PR
Sage-Bionetworks-IT/organizations-infra#859. update to the new role names
depends on Sage-Bionetworks-IT/organizations-infra#859
=> [IT-2768] Update role name for CI

templates/essentials.yaml
Using an `!ImportValue` makes one template depend on another. In this case the essentials stack depends on the OIDC stack. When we attempted to update the OIDC stack in PR https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/859 we got the following error..
```
Export us-east-1-sagebase-github-oidc-sage-bionetworks-it-ProviderRoleArn-organizationsinfra
cannot be deleted as it is in use by essentials
```
This required a temporary fix with PR https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/863
The right fix for this problem is to make the dependency a little looser.  We setup a parameter to pass in the values for the dependency.
=> [IT-2768] Remove importvalue from essentials template

templates/essentials.yaml
small fix error from PR #387 
KmsInfraKeyPrincipals in essentials.yaml needs to be a list of strings
=> fix KmsInfraKeyPrincipals parameter

templates/IAM/github-oidc-provider.j2
Allow user to specify max session duration when assuming a role
=> add MaxSessionDuration to GH OIDC role parameter

templates/IAM/github-oidc-provider.j2
Github requires the AWS OIDC role to have explicit access to github environments as noted in [GH issue 452](https://github.com/aws-actions/configure-aws-credentials/issues/452). Otherwise the following error will occur when attempting to assume the OIDC role in GH actions..
```
Error: Credentials could not be loaded, please check your action inputs: Could
not load credentials from any providers
```
This change enables GH OIDC access to GH environment.
=> GH OIDC access to environments

templates/bootstrap.yaml
AWS does not allow mixing ACLs and bucket policy configurations. AWS recommends not using ACLs going forward[1] so we remove references to ACLs.
[1] https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html
=> Fix bootstrap template

templates/S3/temp-data-bucket.yaml
In SWC-6527, we need a bucket to temporarily store results of playwright tests (the files will be uploaded by GH workflow with OIDC) and retrieved for analysis as needed using the CLI/console). This PR creates a bucket with lifecycle expiration that expires the files after a number of days.
Primary user is the SWC project but other projects are looking at similar pattern so aws-infra seemed a more logical spot for the template.
=> IT-3333: Add template to create a bucket for temporary data

templates/bootstrap.yaml, templates/essentials.yaml
Our bootstrap templates create public buckets to store cloudformation and lambda artifacts which is what we prefer. AWS changed the default account behavior to not allow creating public buckets[1].  To create public bucket we now must explicitly state that we want them to be public. This change does that.
[1] https://repost.aws/questions/QUMcgxysOFRBmKIt9KRkYccg/api-s3-putbucketpolicy-access-denied-error-during-a-cloudformation-stack-creation
=> [IT-3313] Explicitly create public buckets

templates/IAM/snowflake-bucket-access.yaml
This PR fixes the bucket permissions. The resource is the arn of the bucket and should not include the prefix.
=> IT-3362: Fix policy

templates/bootstrap.yaml
The cfn-macro-ssm-param that uses the lambda execution role was not creating logs in cloudwatch because it lacked the permission to allow it.  We need to give it the AWSLambdaBasicExecutionRole to allow AWS to create cloudwatch logs for the lambda.
=> [IT-3425] Add policy to lambda role

templates/S3/synapse-external-bucket.j2
Resolve an error deploying `S3/synapse-external-bucket.j2` by upgrading the python version in a nested lambda template.
=> [IT-3466] Upgrade cfn-cr-same-region-bucket-download version

.cfnlintrc.yaml, templates/Cloudwatch/CrossAccountSharingRole-AccountList.yaml, templates/Cloudwatch/Link-Management-Account.yaml
move files from org-formation[1] repo to here so it can be shared from multiple deployments.
[1] https://github.com/Sage-Bionetworks-IT/organizations-infra/tree/master/org-formation/740-cloudwatch-dashboard
=> [IT-3471] templates to setup cloudwatch dashboard

templates/S3/synapse-external-bucket.j2
Collaborators who are accessing a bucket created from the synapse-external-bucket.j2 template are encountering "Access denied when performing HeadObject" errors. This PR addresses this issue by explicitly granting HeadObject permissions to principals who have read access to the bucket.
=> add HeadObject to Read Object Access Permissions

templates/S3/synapse-external-bucket.j2
Due to a failed deployment using HeadObject in scicomp (https://github.com/Sage-Bionetworks/scicomp-provisioner/actions/runs/8527855786/job/23360215378), this PR replaces HeadObject with GetObjectAttributes
=> add GetObjectAttributes to synapse external bucket template

templates/S3/synapse-external-bucket.j2
Following up on Slack thread re: moving objects in an external bucket and running into 'An error occurred (AccessDenied) when calling the GetObjectTagging operation: Access Denied', this PR adds the permissions to the grantees.
=> Add *ObjectTagging perms

templates/vpc.yaml
Add an optional OpenSearch Serverless VPC endpoint to the VPC
=> IT-4226: Add option OSS VPC endpoint for the VPC

templates/ImageBuilder/amazon-linux-2023-agora-bastian.yaml
Add a template for the AWS image builder to build an image for the agora data manager[1] bastian host which is used to update agora databases.
[1] https://github.com/Sage-Bionetworks/agora-data-manager/settings/actions/runners
=> [IT-4225] Template for image builder

templates/ImageBuilder/amazon-linux-2023-agora-bastian.yaml
Allow user to set the volume size of the AMI when using the image builder template.
=> [IT-3831] Add volume parameter for image builder

templates/NextflowTower/nextflow-launch.yaml
fix the following..
```
The resource ComputeEnvironmentOnDemand is in a CREATE_FAILED state
This AWS::Batch::ComputeEnvironment resource is in a CREATE_FAILED state.
Resource handler returned message: "Error executing request, Exception : Resource minvCpus is required
```
=> [IT-2361] Fix template

templates/NextflowTower/nextflow-launch.yaml
* Fix launch template reference.  It can only take one of name or id.
* Fix batch role to resolve the following stabalization failure:
```
Resource handler returned message: "Resource of type
'AWS::Batch::ComputeEnvironment' with identifier
'arn:aws:batch:us-east-1:035458030717:compute-environment/ComputeEnvironmentSpot-eULJVaK00uH15ZfV'
did not stabilize."
```
=> [IT-2361] Fix nextflow batch compute env template

templates/ImageBuilder/cis-for-eb-image-pipeline-template.yaml
This PR adds a template to create an image builder pipeline to build a CIS Level 1 hardened image which will work with Elastic Beanstalk, for use by Synapse.
=> PLFM-8908 template to add CIS Level 1 image image builder for Synapse

templates/Billing/budgets-transfer-costs.yaml
Duplicate the budget template, adding a cost filter for data-transfer usage types. The list of usage types was found using Cost Explorer. The format of the usage type string was verified by manually creating a budget in AWS and using `aws budgets describe-budgets` to view the auto-generated cost filter.
Docs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-budgets-budget-budgetdata.html https://docs.aws.amazon.com/cost-management/latest/userguide/budgets-create-filters.html https://docs.aws.amazon.com/cli/latest/reference/budgets/describe-budgets.html
=> [IT-4269] Add a template for a data transfer budget

templates/S3/synapse-external-bucket.j2
Security hub will report finding
`2.1.5.2 S3 Block Public Access setting should be enabled at the bucket-level` if `Block all public access` is not enabled on non-public buckets.  We enable that configuration for synapse buckets.
=> Resolve Security hub 2.1.5.2 finding

templates/ImageBuilder/cis-for-eb-image-pipeline-template.yaml
It looks like step names can't contain periods.  
I removed the periods and "manually" ran the CF template to make sure there were not any other issues.
=> SAGL-72: Fixed illegal step names
